# Generated by Django 5.2.8 on 2025-11-29 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="notes.category",
            ),
        ),
    ]
