# Generated by Django 5.2.4 on 2025-12-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0007_category_slug_category_unique_category_per_user"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="category",
            name="unique_category_per_user",
        ),
    ]
