# Generated by Django 5.2.4 on 2025-12-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0008_remove_category_unique_category_per_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
    ]
